# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20171209_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writes',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='writes',
            name='bookId',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='libraryapp.Author'),
        ),
        migrations.DeleteModel(
            name='Writes',
        ),
    ]
