# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_auto_20171209_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='writes',
            unique_together=set([('authorId', 'bookId')]),
        ),
    ]
