# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_auto_20171209_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='publisherId',
            new_name='publisher',
        ),
    ]
