# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_auto_20171210_2146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bortransaction',
            unique_together=set([('copy', 'reader')]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('copy', 'reader')]),
        ),
    ]
